# Run all three servers for the Human Detection Project
# This script launches MediaMTX, Node.js server, and Python YOLO analyzer in separate windows

$ProjectRoot = $PSScriptRoot

Write-Host "===========================================
" -ForegroundColor Cyan
Write-Host "   Human Detection System Launcher" -ForegroundColor Cyan
Write-Host "===========================================" -ForegroundColor Cyan
Write-Host ""

# Video Source Selection Menu
Write-Host "Select Video Source:" -ForegroundColor Yellow
Write-Host "  1. Webcam (Default Camera)" -ForegroundColor White
Write-Host "  2. DJI Drone (RTSP via MediaMTX)" -ForegroundColor White
Write-Host "  3. Custom RTSP/RTMP URL" -ForegroundColor White
Write-Host ""

$Choice = Read-Host "Enter your choice (1-3)"

switch ($Choice) {
    "1" {
        $VideoSource = "0"
        $UseDrone = $false
        Write-Host "Using Webcam" -ForegroundColor Green
    }
    "2" {
        $VideoSource = '"rtsp://localhost:8554/drone"'
        $UseDrone = $true
        Write-Host "Using DJI Drone RTSP Stream" -ForegroundColor Green
    }
    "3" {
        $CustomURL = Read-Host "Enter custom RTSP/RTMP URL"
        $VideoSource = "`"$CustomURL`""
        $UseDrone = $true
        Write-Host "Using Custom URL: $CustomURL" -ForegroundColor Green
    }
    default {
        Write-Host "Invalid choice. Defaulting to Webcam." -ForegroundColor Yellow
        $VideoSource = "0"
        $UseDrone = $false
    }
}

Write-Host ""

# Check if MediaMTX exists (only if drone or custom URL selected)
if ($UseDrone) {
    $MediaMTXPath = Join-Path $ProjectRoot "rtsp\mediamtx.exe"
    if (-not (Test-Path $MediaMTXPath)) {
        Write-Host "WARNING: mediamtx.exe not found in rtsp\ folder!" -ForegroundColor Yellow
        Write-Host "MediaMTX is required for drone/RTSP streaming." -ForegroundColor Yellow
        Write-Host "Download from: https://github.com/bluenviron/mediamtx/releases/tag/v1.15.2" -ForegroundColor Cyan
        Write-Host ""
        $Continue = Read-Host "Continue without MediaMTX? (y/n)"
        if ($Continue -ne "y") {
            exit 1
        }
        $StartMediaMTX = $false
    } else {
        $StartMediaMTX = $true
    }
} else {
    $StartMediaMTX = $false
}

# 1. Start MediaMTX Server (if needed)
if ($StartMediaMTX) {
    Write-Host "Starting MediaMTX RTSP/RTMP Server..." -ForegroundColor Green
    Start-Process powershell -ArgumentList @(
        "-NoExit",
        "-Command",
        "Set-Location '$ProjectRoot\rtsp'; Write-Host 'MediaMTX Server Starting...' -ForegroundColor Cyan; .\mediamtx.exe"
    ) -WindowStyle Normal
    Start-Sleep -Seconds 3
} else {
    Write-Host "Skipping MediaMTX (not required for webcam)" -ForegroundColor Gray
}

# 2. Write video source to config file
$ConfigPath = Join-Path $ProjectRoot "Prototype\config.py"
$ConfigContent = @"
# Video Source Configuration
# This file is auto-generated by run_project.ps1

# VIDEO_SOURCE can be:
# - 0 for webcam (default camera)
# - 1 for second camera
# - "rtsp://localhost:8554/drone" for DJI drone via MediaMTX
# - Any custom RTSP/RTMP URL

VIDEO_SOURCE = $VideoSource
"@

Set-Content -Path $ConfigPath -Value $ConfigContent
Write-Host "Config file created with VIDEO_SOURCE = $VideoSource" -ForegroundColor Gray
Write-Host ""

# 3. Start Node.js Web Server
Write-Host "Starting Node.js Web Server..." -ForegroundColor Green
Start-Process powershell -ArgumentList @(
    "-NoExit",
    "-Command",
    "Set-Location '$ProjectRoot\Prototype'; Write-Host 'Node.js Server Starting on http://localhost:3000' -ForegroundColor Cyan; node server.js"
) -WindowStyle Normal

Start-Sleep -Seconds 3

# 4. Start Python YOLO Analyzer
Write-Host "Starting Python YOLO Analyzer..." -ForegroundColor Green
Start-Process powershell -ArgumentList @(
    "-NoExit",
    "-Command",
    "Set-Location '$ProjectRoot\Prototype'; Write-Host 'Python YOLO Analyzer Starting...' -ForegroundColor Cyan; Write-Host 'Video Source: $VideoSource' -ForegroundColor Yellow; python yolo_analyzer.py"
) -WindowStyle Normal

Start-Sleep -Seconds 2

Write-Host ""
Write-Host "All servers started successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "Web Interface:    http://localhost:3000" -ForegroundColor Yellow
if ($StartMediaMTX) {
    Write-Host "MediaMTX UI:      http://localhost:8888" -ForegroundColor Yellow
    Write-Host "RTSP Stream:      rtsp://localhost:8554/drone" -ForegroundColor Yellow
}
Write-Host ""
Write-Host "Press Ctrl+C in each window to stop the servers" -ForegroundColor Gray
Write-Host ""
